// packages/react/src/components/Button/Button.tsx
import type { ButtonProps } from '@/core/types/Button/button';

export const Button = ({ variant = 'primary', size = 'md', disabled = false }: ButtonProps) => {
	const baseClass = 'taylux-btn';
	const classes = [
		baseClass,
		`${baseClass}--${variant}`,
		`${baseClass}--${size}`,
		disabled ? `${baseClass}--disabled` : '',
	]
		.filter(Boolean)
		.join(' ');

	return <button className={classes}>ok</button>;
};

// packages/vue/src/components/Button/Button.vue
<script setup lang="ts">
import type { ButtonProps } from '@/core/types/Button/button.js';
withDefaults(defineProps<ButtonProps>(), {
	size: 'md',
	variant: 'primary',
	loading: false,
	disabled: false,
	loadingPosition: 'right',
});

defineEmits<{
	(e: 'click', event: MouseEvent): void;
}>();
</script>

<template>
	<button @click="$emit('click', $event)">
		<slot />
	</button>
</template>
